name: Run Python script on index.html update
on:
  push:
    paths:
      - 'index.html'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install beautifulsoup4==4.10.0
      - name: Run Python script
        run: python main.py
